version: '3.8'

services:
  python-http-server:
    image: marcelocollyer/python:latest
    restart: always
    build:
      context: ../python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    healthcheck:
      test: curl --fail http://localhost:8000/ || exit 1
      interval: 5s
      timeout: 30s
      retries: 2

  node-http-server:
    image: marcelocollyer/node:latest
    restart: always
    build:
      context: ../node
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      python-http-server:
        condition: service_healthy             
